// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for HomePage documents */
interface HomepageDocumentData {
  /**
   * hello field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hello
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  hello: prismicT.KeyTextField;
  /**
   * heading field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismicT.KeyTextField;
  /**
   * labelButton field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.labelbutton
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  labelbutton: prismicT.KeyTextField;
}
/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for Question documents */
interface QuestionDocumentData {
  /**
   * title field in *Question*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * description field in *Question*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * category field in *Question*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: question.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  category: prismicT.SelectField<"maths" | "français">;
  /**
   * points field in *Question*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: question.points
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  points: prismicT.NumberField;
  /**
   * Slice Zone field in *Question*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: question.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<QuestionDocumentDataSlicesSlice>;
}
/**
 * Slice for *Question → Slice Zone*
 *
 */
type QuestionDocumentDataSlicesSlice = ResponseSlice;
/**
 * Question document from Prismic
 *
 * - **API ID**: `question`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuestionDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<QuestionDocumentData>,
    "question",
    Lang
  >;
export type AllDocumentTypes = HomepageDocument | QuestionDocument;
/**
 * Primary content in Response → Primary
 *
 */
interface ResponseSliceDefaultPrimary {
  /**
   * Title field in *Response → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: response.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.TitleField;
  /**
   * Description field in *Response → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A nice description of your feature
   * - **API ID Path**: response.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * isGoodAnswer field in *Response → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: response.primary.isgoodanswer
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  isgoodanswer: prismicT.BooleanField;
}
/**
 * Default variation for Response Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Response`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ResponseSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<ResponseSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Response*
 *
 */
type ResponseSliceVariation = ResponseSliceDefault;
/**
 * Response Shared Slice
 *
 * - **API ID**: `response`
 * - **Description**: `Response`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ResponseSlice = prismicT.SharedSlice<
  "response",
  ResponseSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      HomepageDocumentData,
      HomepageDocument,
      QuestionDocumentData,
      QuestionDocumentDataSlicesSlice,
      QuestionDocument,
      AllDocumentTypes,
      ResponseSliceDefaultPrimary,
      ResponseSliceDefault,
      ResponseSliceVariation,
      ResponseSlice,
    };
  }
}
